on:
  # manually running a workflow
  workflow_dispatch:
  # upon pull requests
  pull_request:
  # upon push to 'master' branch
  push:
    branches:
    - master
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install deps
      # texlive-lang-cjk -> xeCJK.sty
      # texlive-lang-chinese -> ctexhook.sty
      # texlive-fonts-recommended -> pzdr.tfm (required by mktextfm pzdr)
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends make ghostscript
        sudo apt-get install -y --no-install-recommends latexmk texlive-xetex
        sudo apt-get install -y --no-install-recommends texlive-lang-cjk texlive-lang-chinese
        sudo apt-get install -y --no-install-recommends fonts-ibm-plex fonts-noto-cjk texlive-fonts-recommended
    - name: install fontawesome5
      # the shipped texlive is 2021 and is older than the remote (currently 2023),
      # so need to manually download the package and install it.
      run: |
        sudo apt-get install -y --no-install-recommends wget xz-utils
        wget --no-check-certificate https://mirror.ctan.org/systems/texlive/tlnet/archive/fontawesome5.tar.xz
        tlmgr --usermode init-usertree
        tlmgr --usermode install --file fontawesome5.tar.xz
    - name: build pdfs
      run: make
